### ISSUE TITLE
Send image

### ISSUE THREAD

**Issue by sanchetkore** [baldarn/whatsapper-ha-integration#6]
I know we can send Image now also, but I have to convert it to base64 before sending which is a lengthy process and a load on cpu. It would be best if we could send image directly using img path

**Comment by baldarn** [comment]
the library used in the system allows only base64 

https://docs.wwebjs.dev/MessageMedia.html

how would you imagine this to work?

**Comment by edgarfroes** [comment]
Here's a script to convert an image to base64 and send it to WhatsApp ([source](https://cmacetko.medium.com/home-assistant-convertendo-arquivo-em-base64-091f7c8b58ed)):

```
alias: servico_1
sequence:
  - variables:
      arquivo_nome: "{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  - service: camera.snapshot
    data:
      entity_id: camera.quarto_main
      filename: /config/www/{{ arquivo_nome }}
  - service: shell_command.get_base64_image
    data:
      arquivo: /config/www/{{ arquivo_nome }}
    response_variable: arquivo_raw
  - service: notify.whatsapp
    data:
      message: Foto do Quarto
      data:
        arquivo: "{{ arquivo_raw.stdout }}"
mode: single
```
